config/routes.rb
Rails.application.routes.draw do

  root 'searches#new'

  resources :acted_ins
  resources :movies
  resources :actors

  resources :searches, only: [:new, :create, :index]

end

app/models/acted_in.rb
class ActedIn
  include Neo4j::ActiveRel
  include Neo4j::Timestamps

  from_class  :Actor
  to_class    :Movie
  type 'acted_in'

  property :role, type: String

  validates_presence_of :role

  before_validation :standardize_role
  after_create :create_worked_withs

  def standardize_role
    self.role = role.titleize.squish
  end

  def create_worked_withs
    movie.actors_excluding(actor).each do |coworker|
      puts WorkedWith.create(from_node: actor, to_node: coworker, movie: movie.title)
      puts WorkedWith.create(from_node: coworker, to_node: actor, movie: movie.title)
    end
  end

  def actor
    self.from_node
  end

  def movie
    self.to_node
  end

end

app/controllers/acted_ins_controller.rb
class ActedInsController < ApplicationController
  before_action :set_acted_in, only: [:show, :edit, :update, :destroy]
  before_action :set_actor_and_movie, only: [:create, :update]
  before_action :set_actors_and_movies, only: [:new, :edit]

  # GET /acted_ins
  # GET /acted_ins.json
  def index
    @acted_ins = ActedIn.all
  end

  # GET /acted_ins/1
  # GET /acted_ins/1.json
  def show
  end

  # GET /acted_ins/new
  def new
    @acted_in = ActedIn.new
  end

  # GET /acted_ins/1/edit
  def edit
  end

  # POST /acted_ins
  # POST /acted_ins.json
  def create
    @acted_in = ActedIn.new(acted_in_params.merge(rel_params))

    respond_to do |format|
      if @acted_in.save
        format.html { redirect_to @acted_in, notice: 'Acted in was successfully created.' }
        format.json { render :show, status: :created, location: @acted_in }
      else
        format.html { render :new }
        format.json { render json: @acted_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acted_ins/1
  # PATCH/PUT /acted_ins/1.json
  def update
    respond_to do |format|
      if @acted_in.update(acted_in_params)
        format.html { redirect_to @acted_in, notice: 'Acted in was successfully updated.' }
        format.json { render :show, status: :ok, location: @acted_in }
      else
        format.html { render :edit }
        format.json { render json: @acted_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acted_ins/1
  # DELETE /acted_ins/1.json
  def destroy
    @acted_in.destroy
    respond_to do |format|
      format.html { redirect_to acted_ins_url, notice: 'Acted in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acted_in
      @acted_in = ActedIn.find(params[:id])
    end

    def set_actor_and_movie
      @movie = Movie.find(params[:movie])
      @actor = Actor.find(params[:actor])
    end

    def set_actors_and_movies
      @actors = Actor.all
      @movies = Movie.all
    end

    def rel_params
      {from_node: @actor, to_node: @movie}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acted_in_params
      params.require(:acted_in).permit(:role)
    end
end

app/helpers/acted_ins_helper.rb
module ActedInsHelper
end

app/views/acted_ins/_form.html.erb
<%= form_for(@acted_in) do |f| %>
  <% if @acted_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acted_in.errors.count, "error") %> prohibited this acted_in from being saved:</h2>

      <ul>
      <% @acted_in.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :actor %>
    <%= select_tag :actor, options_from_collection_for_select(@actors, :uuid, :name) %>
  </div>

  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>

  <div class="field">
    <%= label_tag :movie %>
    <%= select_tag :movie, options_from_collection_for_select(@movies, :uuid, :title) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acted_ins/edit.html.erb
<h1>Editing Performance</h1>

<%= render 'form' %>

<%= link_to 'Show', @acted_in %> |
<%= link_to 'Back', acted_ins_path %>

app/views/acted_ins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Performances</h1>

<table>
  <thead>
    <tr>
      <th>Actor</th>
      <th></th>
      <th>Role</th>
      <th></th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acted_ins.each do |acted_in| %>
      <tr>
        <td><%= acted_in.from_node.name %></td>
        <td>acted as</td>
        <td><%= acted_in.role %></td>
        <td>in</td>
        <td><%= acted_in.to_node.title %></td>
        <td><%= link_to 'Show', acted_in %></td>
        <td><%= link_to 'Edit', edit_acted_in_path(acted_in) %></td>
        <td><%= link_to 'Destroy', acted_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Performance', new_acted_in_path %>

app/views/acted_ins/new.html.erb
<h1>New Performance</h1>

<%= render 'form' %>

<%= link_to 'Back', acted_ins_path %>

app/views/acted_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Actor:</strong>
  <%= @acted_in.from_node.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @acted_in.role %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @acted_in.to_node.title %>
</p>

<%= link_to 'Edit', edit_acted_in_path(@acted_in) %> |
<%= link_to 'Back', acted_ins_path %>